### Register User
POST http://localhost:5000/auth/users
Content-Type: application/json

{
  "firstName": "author2",
  "lastName": "",
  "email": "author2@mail.com",
  "role":"AUTHOR",
  "password": "author2",
  "profileImageUrl": "https://example.com/avatars/user.png"
}


### Create new Article
POST http://localhost:5000/author-api/article
Content-Type: application/json

{
  "author":"69b45eae284e64fb264e1962",
  "title":"Article-2 by Author 2",
  "category":"CS",
  "content":"test article on CS"
  
}



### Author Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email":"author2@gmail.com",
  "password":"author2"
}


### Author logout
GET http://localhost:5000/auth/logout


### Read own articles
GET http://localhost:5000/author-api/articles

### Update article by author
PUT http://localhost:5000/author-api/articles
Content-Type: application/json

{
  "articleId":"69b3c780ad975da58dbd3ba1",
  "title":"Article-2 by Author 1",
  "category":"AI",
  "content":"test article on AI and its updated"
  
}


### Delete / restore anarticle by Article ID (soft delete)
PATCH http://localhost:5000/author-api/articles
Content-Type: application/json

{
  "articleId":"69b3a8f881ab391ebe9a7435",
  "isArticleActive":true
}