### Register User
POST http://localhost:5000/auth/users
Content-Type: application/json

{
  "firstName": "author2",
  "lastName": "",
  "email": "author2@gmail.com",
  "role":"AUTHOR",
  "password": "author2",
  "profileImageUrl": "https://example.com/avatars/user.png"
}

### User Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email":"user1@gmail.com",
  "password":"user1"
}

### User logout
GET http://localhost:5000/auth/logout


### Read articles of all authors
GET http://localhost:5000/user-api/articles



### Add comment by user to an article
PUT http://localhost:5000/user-api/articles
Content-Type: application/json

{
  "articleId":"69b45f09284e64fb264e196a",
  "comment":"This is a useful article"
}

### change password
PUT http://localhost:5000/auth/password
Content-Type: application/json

{
  "currentPassword":"user1",
  "newPassword":"user"
}